/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "初始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Unicorns:": "独角兽:",
    "Fairies:": "仙女:",
    "Zombies": "僵尸",
    "Upgrades": "升级",
    "Warning:": "警告:",
    "Stats": "统计",
    "⏸️ Pause": "⏸️ 暂停",
    "⸸️ Pause": "⸸️ 暂停",
    "⏰ Welcome Back!": "⏰ 欢迎回来!",
    "⏰ Time & Progress": "⏰ 时间 & 进度",
    "✅ Loaded!": "✅ 已加载!",
    "✅ You will keep:": "✅ 你将保留:",
    "✖️ Cancel": "✖️ 取消",
    "✖️ Close": "✖️ 关闭",
    "✨ Begin New Journey": "✨ 初始新的旅程",
    "✨ Continue Adventure": "✨ 继续冒险",
    "✨ Resources Generated": "✨ 生成资源",
    "❌ Cancel": "❌ 取消",
    "❌ You will lose:": "❌ 你将失去:",
    "❌ You will lose EVERYTHING:": "❌ 你将失去一切:",
    "❌ No, Keep My Progress": "❌ 不，保留我的进度",
    "🏭 Producers Built": "🏭 生产商建立",
    "🎯 Upgrades Purchased": "🎯 购买的升级",
    "🎉 Ascension Complete!": "🎉 转生完成!",
    "👆 Manual Actions": "👆 手动动作",
    "👑 Ascend!": "👑 转生!",
    "💾 Save": "💾 保存",
    "📁 Load": "📁 加载",
    "📁 Load Save": "📁 加载存档",
    "Click me!": "点我!",
    "Close": "关闭",
    "Cloud Producers:": "云朵生产商:",
    "Comes to Earth": "来到地球",
    "Builders": "建设者",
    "Congratulations!": "恭喜!",
    "Continue playing": "继续游戏",
    "Distance traveled:": "旅行距离:",
    "Distance left:": "剩余距离:",
    "/ sec)": "/ 秒)",
    ", with contributions from Gabriel Gimenez Franz.": "，Gabriel Gimenez Franz也做出了贡献。",
    ", and Shooting Star icon designed by": "，流星图标来自",
    "Rainbows": "彩虹",
    "Rainbow Rerolls:": "彩虹重掷:",
    "Rainbows:": "彩虹:",
    "Speed:": "速度:",
    "Stardust": "星尘",
    "Stardust:": "星尘:",
    "Stardust Producers:": "星尘生产者:",
    "Start over": "重新初始",
    "The Fairy Queen": "仙女女王",
    "Time left:": "剩余时间:",
    "Total Gold:": "金币总计:",
    "Total Unicorns:": "独角兽总计:",
    "Total Upgrades:": "升级总计:",
    "Total Zombies:": "僵尸总计:",
    "Total Rainbows:": "彩虹总计:",
    "Total Time Played:": "总计游戏时长:",
    "Total Royal Essence:": "皇家精华总计:",
    "Unicorn Rerolls:": "独角兽重掷:",
    "Unicorn Clicks:": "独角兽点击:",
    "Unicorn Production Boost": "独角兽生产提升",
    "You gained": "你获得了",
    "You are about to ascend and gain": "你即将转生并获得",
    "You were offline for:": "你离线了:",
    "Your saved game data": "你保存了游戏数据",
    "Royal Chamber": "皇家大厅",
    "Royal Essence:": "皇家精华:",
    "Royal Essence!": "皇家精华!",
    "Royal Essence.": "皇家精华.",
    "Special Upgrades:": "特殊升级:",
    "Thanks to your skill, the Fairy Queen reached Earth much faster than we thought. Today is a day of celebration for the Fairies and Unicorns!": "多亏了你的技能，仙女女王到达地球的速度比我们想象的要快得多。今天是仙女和独角兽的节日！",
    "The Leprechaun uses his gold to craft powerful magical enhancements!": "小妖精用他的金币来制造强大的魔法强化！",
    "Unicorns or less": "独角兽或以下",
    "Unicorns make": "独角兽使",
    "📤 Export": "📤 导出",
    "📥 Import": "📥 导入",
    "📤 Export Save Data": "📤 导出存档数据",
    "📥 Import Save Data": "📤 导入存档数据",
    "🗑️ Hard Reset": "🗑️ 硬重置",
    "🗑️ Hard Reset Confirmation": "🗑️ 硬重置确认",
    "🗑️ Yes, Reset Everything": "🗑️ 是，重置一切",
    "🧚‍♀️🦄 Creatures Generated": "🧚‍♀️🦄 生成的生物",
    "About": "关于",
    "Add one more upgrade card to choose from": "增加一张升级卡供选择从",
    "Autobuy 1/sec unless there are": "自动购买1次/秒，除非有",
    "Click to boost Unicorns": "点击提升独角兽",
    "Condensed magical power from your proximity to the Fairy Queen. ": "你和仙女女王的亲密接触凝聚了魔法力量。",
    "Gold:": "金币:",
    "Good Ware": "良好的制品",
    "Images designed by": "图片设计：",
    "Max": "最大",
    "Max Queen Speed:": "最大女王速度:",
    "Next:": "下一个:",
    "Queen": "女王",
    "Queen Accelerators": "女王加速器",
    "Queen progress and speed": "女王进度和速度",
    "Rainbow Progress:": "彩虹进度:",
    "Rainbows are boosting Fairies": "彩虹提升仙女",
    "Rainbows are boosting Unicorns and Zombie Unicorns": "彩虹提升独角兽和僵尸独角兽",
    "each": "每个",
    "Fairies make": "仙女使",
    "Fairy Rerolls:": "仙女重掷:",
    "Fairy Clicks:": "仙女点击:",
    "Fairy Molecules/sec": "仙女分子/秒",
    "Fairy Production Boost": "仙女生产提升",
    "Find several methods to speed her up,": "找到几种方法让她加快速度，",
    "Formula: √(distance traveled) + √(gold) + √(time in minutes) = Royal Essence per ascension.": "公式：√（旅行距离）+ √（金币）+ √（分钟）= 每次转生的皇家精华。",
    "from": "从",
    "Gained from:": "获得自:",
    "Glitter": "闪光",
    "Glitter Producers:": "闪光生产者:",
    "Games Saved:": "游戏保存:",
    "Game Statistics": "游戏统计",
    "leagues": "里格",
    "leagues/hour": "里格/小时",
    "Leprechaun": "小妖精",
    "Leprechaun Producers:": "小妖精生产商:",
    "Leprechaun's Workshop": "小妖精的工坊",
    "Paste your save data below to load your game:": "将你的保存数据粘贴到下面来加载你的游戏进度：",
    "Production Boosts:": "生产提升:",
    "Please wait while magic loads": "请稍等，魔法正在加载",
    "👑 Royal Ascension": "👑 皇家转生",
    "👑 Ascension Progress": "👑 转生进度",
    "⚠️ Offline efficiency: 50% (can be improved with future upgrades)": "⚠️ 离线效率：50%（以后升级可以提高）",
    "‍♀️ Loading Fairies and Unicorns...": "正在加载仙女与独角兽...",
    "📋 Copy to Clipboard": "📋 复制到剪贴板",
    "All creatures, resources, and producers": "所有生物、资源和生产者",
    "All purchased upgrades and slots": "所有购买的升级和槽位",
    "All Royal Essence and prestige upgrades": "所有皇家精华和声望升级",
    "All statistics and achievements": "所有统计和成就",
    "An incremental game by Eduardo Abel Gimenez": "Eduardo Abel Gimenez的增量游戏",
    "and Eduardo Abel Gimenez, except: Comet icon designed by": "和Eduardo Abel Gimenez，除了: 彗星图标设计来自",
    "and make her arrive as soon as possible.": "让她尽快赶到。",
    "Builders automatically click Fairies and Unicorns for you!": "建设者会自动为你点击精灵和独角兽！",
    "Copy this save data to share or backup your progress:": "复制此存档数据以共享或备份您的进度：",
    "Cost Reductions:": "成本降低:",
    "distance traveled, current gold, and time spent since last ascension. ": "旅行距离，当前金币，距离上次转生的时间",
    "Each Rainbow produces gold for the Leprechaun!": "每一道彩虹都会为小妖精带来金子！",
    "Extra Upgrade Card (Stardust)": "额外升级卡（星尘）",
    "Unicorn Molecules/sec": "独角兽分子/秒",
    "Total Stardust:": "总计星尘:",
    "Total Glitter:": "总计闪光:",
    "Total Fairies:": "总计仙女:",
    "Total Builders:": "总计建设者:",
    "Total Ascensions:": "总计转生:",
    "Total Distance Traveled:": "总计旅行时间:",
    "Time in current Ascension:": "本轮转生用时:",
    "Fairies and Unicorns": "仙女与独角兽",
    "Fairies or less": "仙女以下",
    "Fairies produce +1 more Unicorn molecules per second": "仙女每秒多制造1个独角兽分子",
    "Freepik": "免费",
    "Glitter:": "闪光:",
    "You'll win the game when the Fairy Queen reaches Earth!": "当仙女女王到达地球时，你就赢了！",
    "Zombies can only be obtained through their autobuyers - no manual purchasing!": "僵尸只能通过自动购买获得，无法手动购买！",
    "Visit the Royal Chamber to spend your Royal Essence on permanent upgrades!": "访问皇家大厅，将您的皇家精华用于永久升级！",
    "Unicorns produce +1 more Fairy molecules per second": "独角兽每秒多生产1个仙女分子",
    "Total Queen Accelerators:": "女王加速器总数:",
    "This will permanently delete ALL your progress and return the game to its initial state!": "这将永久删除你所有的进度，并将游戏返回到初始状态！",
    "This action cannot be undone!": "此操作无法撤销！",
    "Make the Fairy Queen travel faster!": "让仙女女王旅行得更快！",
    "✅ Imported!": "✅ 已导入!",
    "💾 Auto": "💾 自动",
    "✅ Saved!": "✅ 已保存!",
    "Click to boost Unicorns and Zombie Unicorns": "点击提升独角兽和僵尸独角兽",
    "Fairies and Zombie Fairies make": "仙女和僵尸仙女使",
    "Fairy Builder Upgrade": "仙女建设者升级",
    "Glitter Producers Boost": "闪光生产者提升",
    "Glitter producers create +25% more glitter": "闪光生产者制造的闪光增加 25%",
    "Fairy Builders autoclick +1 more time per second": "仙女建设者每秒自动点击 +1",
    "Maxed out!": "已满！",
    "Queen Accelerators Cost Reduction (Fairy)": "女王加速器成本降低（仙女）",
    "Queen Accelerators Production Boost (Fairy)": "女王加速器生产提升（仙女）",
    "Rainbows are boosting Fairies and Zombie Fairies": "彩虹提升了仙女和僵尸仙女",
    "Stardust Producers Boost": "星尘生产者提升",
    "Stardust Producers Cost Reduction": "星尘生产者成本降低",
    "Stardust producers costs reduce by 5%": "星尘生产者成本降低 5%",
    "Stardust producers create +25% more stardust": "星尘生产者制造的星尘增加 25%",
    "Unicorns and Zombie Unicorns make": "独角兽和僵尸独角兽使",
    "Unlock by buying the \"Unlock Leprechaun!\" upgrade": "通过购买“解锁小妖精！”升级解锁",
    "Unlock by buying the \"Unlock Rainbows!\" upgrade": "通过购买“解锁彩虹！”升级解锁",
    "Unlock by buying the \"Unlock Zombies!\" upgrade": "通过购买“解锁僵尸！”升级解锁",
    "Unlock by buying the \"Unlock the Royal Chamber!\" upgrade": "通过购买“解锁皇家大厅！”升级解锁",
    ", plus Rainbows": "，加上彩虹",
    "+25% more Royal Essence gained per level": "每级增加25%的皇家精华",
    "🎁 Starting Resources": "🎁 初始资源",
    "👑 Queen and Gold": "👑 女王和金币",
    "🔮 Meta Progression": "🔮 元进程",
    "🧚‍♀️ Production Mastery": "🧚‍♀️ 生产精通",
    "Autobuyers start buying 2 more Zombie Fairies per second, per level.": "自动购买者初始每级每秒购买2个僵尸仙女。",
    "Autobuyers start buying 2 more Zombie Unicorns per second, per level.": "自动购买者初始每级每秒购买2个僵尸独角兽。",
    "Avarice adds 50% more cost reduction to other Leprechaun producers": "贪婪使其他小妖精生产者的成本降低50%",
    "PAUSED!": "已暂停!",
    "New Shoes add 50% more speed": "新鞋增加50%速度",
    "Improve offline efficiency by 10% per level (max 90%)": "每升一级提高离线效率10%（最高90%）",
    "Fairies start producing +1 more Unicorn Molecule per second each": "仙女初始每秒钟多生产1个独角兽分子",
    "Each Stardust producer starts producing +25% more (cumulative)": "每个星尘生产者初始生产产量+25%（累加）",
    "Each Glitter producer starts producing +25% more (cumulative)": "每个闪光生产者初始生产产量+25%（累加）",
    "Each Rainbow produces +25% more Gold per second (cumulative)": "每个彩虹每秒生产金币产量+25%（累加）",
    "Each Cloud produces +25% more Rainbow parts (cumulative)": "每个云朵生产彩虹零件产量+25%（累加）",
    "Each Rainbow boosts each Fairy/Unicorn by +1 more Molecule per second": "每个彩虹每秒提升每个 仙女/独角兽 +1 分子",
    "Queen Accelerators add 50% more speed (cumulative)": "女王加速器增加50%的速度（累加）",
    "Queen starts with double base speed per level": "女王开始时每级的基础速度翻倍",
    "Space Shrink adds 50% more distance reduction": "空间收缩额外增加50%的距离减少效果",
    "Trickery adds 50% more gold production to Rainbows (cumulative)": "诡计为彩虹增加50%的黄金产量（累加）",
    "Unicorns start producing +1 more Fairy Molecule per second each": "独角兽开始每秒多生产1个仙女分子",
    "Zombie Unicorns Autobuyer Upgrade": "僵尸独角兽自动购买者升级",
    "Zombie Fairies Autobuyer Upgrade": "僵尸仙女自动购买者升级",
    "Unicorn Builder Upgrade": "独角兽建设者升级",
    "Zombie Unicorns Autobuyer buys +1 more per second": "僵尸独角兽自动购买者购买每秒+1",
    "Zombie Fairies Autobuyer buys +1 more per second": "僵尸仙女自动购买者购买每秒+1",
    "Unicorn Builders autoclick +1 more time per second": "独角兽建设者自动点击每秒+1",
    "Rainbow Boost": "彩虹提升",
    "Leprechaun's Mastery": "小妖精精通",
    "Fairy Cost Reduction": "仙女成本降低",
    "Fairy costs increase 5% slower": "仙女成本增速降低 5%",
    "Unicorn costs increase 5% slower": "独角兽成本增速降低 5%",
    "Clouds Cost Reduction": "云朵成本降低",
    "Clouds costs reduce by 5%": "云朵成本降低 5%",
    "Glitter producers costs reduce by 5%": "闪光生产者成本降低 5%",
    "Glitter Producers Cost Reduction": "闪光生产者成本降低",
    "Extra Upgrade Card (Glitter)": "额外升级卡 (闪光)",
    "Queen Accelerators Cost Reduction (Unicorn)": "女王加速器成本降低 (独角兽)",
    "Queen Accelerators Production Boost (Unicorn)": "女王加速器生产提升 (独角兽)",
    "All Leprechaun producers are 25% more effective": "所有小妖精生产者效率提升 25%",
    "Each Rainbow boost molecule production by 1 more": "每个彩虹提升分子生产 +1",
    "Boost": "提升",
    "Clouds produce +25% more Rainbow parts per second": "云朵每秒生产的彩虹零件 +25%",
    "Unicorn Cost Reduction": "独角兽成本降低",
    "Click to boost Fairies and Zombie Fairies": "点击提升仙女和僵尸仙女",
    "Your game knowledge and experience": "你的游戏知识和经验",
    "All Prestige Upgrades and Milestones": "所有声望升级和里程碑",
    "All Producers and their amounts": "所有生产者和他们的数量",
    "All purchased upgrades": "所有购买的升级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "www.flaticon.com": "www.flaticon.com",
    "(magicaweb.com)": "(magicaweb.com)",
    "Zlatko Najdenovski": "Zlatko Najdenovski",
    "😴": "😴",
    "🖱️": "🖱️",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Zebra Unicorns: ": "斑马独角兽: ",
    "Zombie Unicorns: ": "僵尸独角兽: ",
    "Zombie Fairies: ": "僵尸仙女: ",
    "Warrior Fairies: ": "战士仙女: ",
    "Unicorn Builder: ": "独角兽建设者: ",
    "Sunny Clouds: ": "晴朗的云: ",
    "String Theory: ": "弦理论: ",
    "Trickery: ": "诡计: ",
    "Rocket: ": "火箭: ",
    "Sentient Clouds: ": "有知觉的云: ",
    "Shooting Star: ": "流星: ",
    "The Fairy Queen is increasing Fairies, Unicorns and Zombies productivity by ": "仙女女王增加仙女，独角兽和僵尸的生产力 ",
    "Chess Unicorns: ": "象棋独角兽: ",
    "Comet: ": "彗星: ",
    "Nocorns: ": "玉米: ",
    "Nature Fairies: ": "自然仙女: ",
    "New Shoes: ": "新鞋: ",
    "Panda Unicorns: ": "熊猫独角兽: ",
    "Glitter/sec: ": "闪光/秒: ",
    "Alien Clouds: ": "外星人云: ",
    "Avarice: ": "贪婪: ",
    "Bard Fairies: ": "吟游仙女: ",
    "Stardust/sec: ": "星尘/秒: ",
    "Space Shrink: ": "空间收缩: ",
    "Fairy Builder: ": "仙女建设者: ",
    "Pirate Fairies: ": "海盗仙女: ",
    "Rainbow parts/sec: ": "彩虹零件/秒: ",
    "Winged Clouds: ": "飞翔的云: ",
    "Use it to purchase permanent upgrades that carry over between runs.": "使用它来购买运行之间的永久升级。",
    "✨ Glitter: ": "✨ 闪光: ",
    "⭐ Stardust: ": "⭐ 星尘: ",
    "🍀 Gold: ": "🍀 金币: ",
    "🧚‍♀️ Fairies: ": "🧚‍♀️ 仙女: ",
    "Auto-Autoclickers ": "自动-自动点击器 ",
    "Queen Accelerators Power ": "女王加速器之力 ",
    "Trickery Power ": "诡计之力 ",
    "Space Shrink Power ": "空间收缩之力 ",
    "Avarice Power ": "贪婪之力 ",
    "Stardust Production ": "星尘生产 ",
    "Rainbows Molecule Production ": "彩虹分子生产 ",
    "Rainbows Gold Production ": "彩虹金币生产 ",
    "Rainbows Genesis ": "彩虹起源 ",
    "Clouds Production ": "云朵生产 ",
    "Unicorns' Favor ": "独角兽的恩惠 ",
    "Fairies' Favor ": "仙女的恩惠 ",
    "Unicorn Mastery ": "独角兽精通 ",
    "Fairy Mastery ": "仙女精通 ",
    "Stardust Galore ": "大量星尘 ",
    "Glitter Galore ": "大量闪光 ",
    "Rainbow Genesis ": "彩虹起源 ",
    "Glitter Production ": "闪光生产 ",
    "More Zombie Unicorns ": "更多僵尸独角兽 ",
    "More Zombie Fairies ": "更多僵尸仙女 ",
    "New Shoes Power ": "新鞋之力 ",
    "Offline Mastery ": "离线精通 ",
    "Royal Speed ": "皇家速度 ",
    "Royal Gathering ": "皇家采集 ",
    "🌈 Rainbows: ": "🌈 彩虹: ",
    "🦄 Unicorns: ": "🦄 独角兽: ",
    "Upgrade Slots purchased": "购买的升级槽位",
    "Royal Essence: ": "皇家精华: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " each)": " 每个)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)K \(([\d\.]+)$/,
    /^([\d\.]+)K \(([\d\.]+)K$/,
    /^([\d\.]+)Kx$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \(([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Queen distance traveled \((.+) leagues\)$/, '女王旅行距离（$1 里格）'],
    [/^All Resources \((.+) Glitter, (.+) Stardust, (.+) Gold\)$/, '所有资源（$1 闪光，$2 星尘，$3 金币）'],
    [/^All Fairies and Unicorns \((.+) and (.+)\)$/, '所有仙女和独角兽（$1 和 $2）'],
    [/^All Rainbows \((.+)\)$/, '所有彩虹（$1）'],
    [/^Start each run with (.+) Fairy and Unicorn Autoclickers per level$/, '开始每次运行每级 $1 仙女和独角兽自动点击器'],
    [/^Start each run with (.+) Unicorns per level$/, '开始每次运行每级 $1 独角兽'],
    [/^Start each run with (.+) Fairies per level$/, '开始每次运行每级 $1 仙女'],
    [/^Start each run with (.+) Stardust per level$/, '开始每次运行每级 $1 星尘'],
    [/^Start each run with (.+) Glitter per level$/, '开始每次运行每级 $1 闪光'],
    [/^Start each run with (.+) Rainbow per level$/, '开始每次运行每级 $1 彩虹'],
    [/^All Queen Accelerators cost (.+) less$/, '所有女王加速器成本降低 $1'],
    [/^All Queen Accelerators are (.+) more effective$/, '所有女王加速器效率提升 $1'],
    [/^Unlock by reaching (.+) Fairies$/, '达到 $1 仙女以解锁'],
    [/^Unlock by reaching (.+) Unicorns$/, '达到 $1 独角兽以解锁'],
    [/^Stardust\/sec: (.+) \((.+) each\)$/, '星尘/秒: $1 ($2 每个)'],
    [/^Reroll for (.+) Fairies$/, '重掷消耗 $1 仙女'],
    [/^Reroll for (.+) Rainbows$/, '重掷消耗 $1 彩虹'],
    [/^Reroll for (.+) Unicorns$/, '重掷消耗 $1 独角兽'],
    [/^Buy for (.+) Rainbows$/, '购买 $1 彩虹'],
    [/^Buy for (.+) Zombie Fairies$/, '购买 $1 僵尸仙女'],
    [/^Buy for (.+) Fairies$/, '购买 $1 仙女'],
    [/^Buy for (.+) Zombie Unicorns$/, '购买 $1 僵尸独角兽'],
    [/^Buy for (.+) Unicorns$/, '购买 $1 独角兽'],
    [/^Buy for (.+) Unicorns Autoclickers$/, '购买 $1 独角兽自动点击器'],
    [/^Buy for (.+) Stardust$/, '购买 $1 星尘'],
    [/^Buy for (.+) Glitter$/, '购买 $1 闪光'],
    [/^Buy for (.+) Fairy Autoclickers$/, '购买 $1 仙女自动点击器'],
    [/^Buy for (.+) Gold 🍀$/, '购买 $1 金币 🍀'],
    [/^Buy (.+) for (.+) Gold 🍀$/, '购买 $1 花费 $2 金币 🍀'],
    [/^Buy (.+) for (.+) Unicorns$/, '购买 $1 花费 $2 独角兽'],
    [/^Buy (.+) for (.+) Fairies$/, '购买 $1 花费 $2 仙女'],
    [/^Buy (.+) for (.+) Stardust$/, '购买 $1 花费 $2 星尘'],
    [/^Buy (.+) for (.+) Glitter$/, '购买 $1 花费 $2 闪光'],
    [/^Autobuy (.+)\/sec unless there are$/, '自动购买$1/秒，除非有'],
    [/^Ascend to get (.+) Royal Essence$/, '转生以获得 $1 皇家精华'],
    [/^Rainbows boost each Unicorn and Zombie Unicorn by (.+) Fairy Molecules\/sec \((.+) each Rainbow\)$/, '彩虹增加每个独角兽和僵尸独角兽 $1 仙女分子/秒（每个彩虹 $2）'],
    [/^Rainbows boost each Fairy and Zombie Fairy by (.+) Unicorn Molecules\/sec \((.+) each Rainbow\)$/, '彩虹增加每个仙女和僵尸仙女 $1 独角兽分子/秒（每个彩虹 $2）'],
    [/^Rainbows boost each Fairy by (.+) Unicorn Molecules\/sec \((.+) each Rainbow\)$/, '彩虹增加每个仙女 $1 独角兽分子/秒（每个彩虹 $2）'],
    [/^👑 Queen Distance: (.+) leagues$/, '👑 女王距离: $1 里格'],
    [/^Rainbows boost each Fairy by (.+) Unicorn Molecules\/sec$/, '彩虹使每个仙女每秒增加 $1 独角兽分子'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Fairy Mol\/sec \($/, '$1 仙女分子\/秒 ('],
    [/^([\d\.,]+) Unicorn Mol\/sec \($/, '$1 独角兽分子\/秒 ('],
    [/^([\d\.,]+) years, ([\d\.,]+) days$/, '$1 年，$2 天'],
    [/^([\d\.,]+) years, ([\d\.,]+) months, ([\d\.,]+) days$/, '$1 年，$2 月，$3 天'],
    [/^([\d\.,]+) days, ([\d\.,]+) hours, ([\d\.,]+) minutes$/, '$1 天，$2 小时，$3 分钟'],
    [/^([\d\.,]+) years$/, '$1 年'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) Fairy Mol\/sec \((.+) each\), plus Rainbows$/, '$1 仙女分子\/秒 ($2 每个), 加上彩虹'],
    [/^(.+) Fairy Mol\/sec \((.+)$/, '$1 仙女分子\/秒 ($2'],
    [/^(.+) Unicorn Mol\/sec \((.+) each\), plus Rainbows$/, '$1 独角兽分子\/秒 ($2 每个), 加上彩虹'],
    [/^(.+) Unicorn Mol\/sec \((.+)$/, '$1 独角兽分子\/秒 ($2'],
    [/^(.+) Speed total \((.+)$/, '$1 总速度 ($2'],
    [/^(.+) autoclicks\/sec total \((.+)$/, '$1 自动点击\/秒 总计 ($2'],
    [/^(.+) gold production per level \((.+) total\)$/, '每级 $1 金币生产 (总计 $2)'],
    [/^(.+) Queen speed per level \((.+) total\)$/, '$每级 1 女王速度 (总计 $2)'],
    [/^(.+) Queen distance per level \(max (.+)\)$/, '每级 $1 女王距离 (最大 $2)'],
    [/^(.+) cost for other Leprechaun producers per level \(max (.+)\)$/, '每级 $1 其他小妖精生产者成本 (最大 $2)'],
    [/^(.+) Royal Essence$/, '$1 皇家精华'],
    [/^Cost: (.+) Fairies each$/, '成本：$1 仙女 每个'],
    [/^Cost: (.+) Unicorns each$/, '成本：$1 独角兽 每个'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);